### ISSUE TITLE
Jsondelete app is not working

### ISSUE THREAD

**Issue by beneditomarques** [drivefast/asterisk-res_json#11]
I have the dialplan bellow:
```
[default]

exten => 999,1,Noop()
 same =>     n,Set(json={"audios":["custom/ivr/audio1","custom/ivr/audio2"]})
 same =>     n,Noop(${JSONELEMENT(json,audios)})
 same =>     n,Noop(${JSONTYPE})
 same =>     n,Noop(${JSONELEMENT(json,audios/0)})
 same =>     n,jsondelete(json,audios/0)
 same =>     n,Noop(${JSONRESULT})
 same =>     n,Noop(${JSONELEMENT(json,audios)})
```

When I call the extension 999, the item 0 of array is not deleted. The code 4 (ASTJSON_NOTFOUND - the expected element could not be found at the given path) is returned:

![image](https://user-images.githubusercontent.com/50053924/119051087-177af100-b999-11eb-8a3b-cd2572f6c808.png)

**Comment by drivefast** [comment]
Can you please try 
`same =>     n,jsondelete(json,/audios/0)`
instead (start the second argument with an `/`), and let me know if it worked. You may also want to try quoting and escaping the path string. Thanks.

**Comment by beneditomarques** [comment]
I've tried before with the methods bellow:

audios/0
/audios/0
/audios/0/
audios/0/
\\/audios\\/0
/audios\\/0

Nothing works.

**Comment by drivefast** [comment]
Thank you, Benedito, i really appreciate the effort put into documenting the issue. I will try to figure out a fix soon, but i cannot give you an exact time right now.

**Comment by beneditomarques** [comment]
OK, thanks. I believe that the problem is the switch bellow, because when I put the function "cJSON_DeleteItemFromArray" before it, the delete of element works:

![image](https://user-images.githubusercontent.com/50053924/119062933-4354a180-b9ae-11eb-8672-4e8678a70498.png)

![image](https://user-images.githubusercontent.com/50053924/119062962-59faf880-b9ae-11eb-8c7f-fa9acb69a961.png)
