### ISSUE TITLE
Further example on json

### ISSUE THREAD

**Issue by fredcwbr** [drivefast/asterisk-res_json#4]
Howdy,

Still didn't figure out how to use JSONPRETTY, but anyway, after lots of digging, got an example that demonstrates how to make a json variable. 
Thought that I should share so some other newbie like me could save time on the learning process., 

On extensions.conf, add an extension (6094 for example), ..

exten => 6094,1,Answer
;;; 
;;;   Add a member on root node  (canal)
;;;
same => n,jsonadd(json **,,** string,**canal**,${EXTEN})
;;;
;;;    Add another member on  root node  (cnl) 
same => n,jsonadd(json **,,** string,**cnl**,${EXTEN})
;;;
;;;    And another  ,, now an array node to  fill up next...
same => n,jsonadd(json **,,** array, **raiz** ,abcd)
;;; 
;;;    fill item on the array 
same => n,jsonadd(json, **raiz** ,string,,abcd)
same => n,jsonadd(json, **raiz** ,number,,1234)
same => n,Set(RCX=JSONPRETTY(json))
same => n,Verbose(${RCX})
same => n,DumpChan(3)

same => n,Hangup
;

When dialing the extension now you get::, ...  

(with a little help of the DumpChan with Verbose(3) ) ... 

````

== Using SIP RTP CoS mark 5
       > 0x7f4664014160 -- Strict RTP learning after remote address set to: 192.168.64.6:8000
    -- Executing [6094@rmtc:1] Answer("SIP/6020-00000004", "") in new stack
       > 0x7f4664014160 -- Strict RTP switching to RTP target address 192.168.64.6:8000 as source
    -- Executing [6094@rmtc:2] jsonadd("SIP/6020-00000004", "json,,string,canal,6094") in new stack
[Nov 15 22:57:05] WARNING[22553][C-00000004]: res_json.c:531 jsonadd_exec: path is empty, adding element to the root
    -- Executing [6094@rmtc:3] jsonadd("SIP/6020-00000004", "json,,string,cnl,6094") in new stack
[Nov 15 22:57:05] WARNING[22553][C-00000004]: res_json.c:531 jsonadd_exec: path is empty, adding element to the root
    -- Executing [6094@rmtc:4] jsonadd("SIP/6020-00000004", "json,,array,raiz,abcd") in new stack
[Nov 15 22:57:05] WARNING[22553][C-00000004]: res_json.c:531 jsonadd_exec: path is empty, adding element to the root
    -- Executing [6094@rmtc:5] jsonadd("SIP/6020-00000004", "json,raiz,string,,abcd") in new stack
    -- Executing [6094@rmtc:6] jsonadd("SIP/6020-00000004", "json,raiz,number,,1234") in new stack
    -- Executing [6094@rmtc:7] Set("SIP/6020-00000004", "RCX=JSONPRETTY(json)") in new stack
    -- Executing [6094@rmtc:8] Verbose("SIP/6020-00000004", "JSONPRETTY(json)") in new stack
JSONPRETTY(json)
    -- Executing [6094@rmtc:9] DumpChan("SIP/6020-00000004", "3") in new stack


......  Other channel stuff.... 

   -- Variables:
    -- RCX=JSONPRETTY(json)
    -- JSONRESULT=0
    -- json={"canal":"6094","cnl":"6094","raiz":["abcd",1234]}
    -- SIPCALLID=mhjzragvevjaovz@alpha.fcwsistemas.com.br
    -- SIPDOMAIN=192.168.32.4
    -- SIPURI=sip:6020@192.168.64.6
````

Best regards, ...

And thank you for the great gig., ..

**Comment by drivefast** [comment]
`same => n,Set(RCX=${JSONPRETTY(json)})`
