### ISSUE TITLE
Asterisk 16 compatible?

### ISSUE THREAD

**Issue by pat2770** [drivefast/asterisk-res_json#5]
Is this module Asterisk 16 compatible? 

Regards
Patrik

**Comment by drivefast** [comment]
I have not tried it with Asterisk 16. The build instructions may not apply anymore.

**Comment by pat2770** [comment]
Hi. I’m on it. Had to change free() to ast_free() to make it compiling. 

I‘ll do some tests on Monday and I‘ll publish a patch if it’s working.

**Comment by fredcwbr** [comment]
> Hi. I’m on it. Had to change free() to ast_free() to make it compiling.
> 
> I‘ll do some tests on Monday and I‘ll publish a patch if it’s working.

Howdy, .. . how did this go?

**Comment by pat2770** [comment]
It worked for me. But I didn’t test it in production. So there might be some more bugs.

**Comment by felipem1210** [comment]
Hello 
I'm also trying to compile the module for asterisk 16, I'm having the same error you described before for compiling. It will be fixed?

Best regards

**Comment by joelsdc** [comment]
+1 here :)

**Comment by felipem1210** [comment]
Joel hi made a fork of the repo with the fix to compile with asterisk 16 this module: https://github.com/felipem1210/asterisk-res_json

**Comment by joelsdc** [comment]
@felipem1210, I just tried your fork and it works perfect!

I switched my automation scripts to point to your repo, thank you for contributing :D :+1:

**Comment by joelsdc** [comment]
@felipem1210 do you think any of these commits are worth adding to your fork?

https://github.com/Koch-AG/asterisk-res_json/commit/ebb39b4577dc2feeff081965149fef8848ed0051
https://github.com/teabreak58/asterisk-res_json/commit/7991c401776d48da08dad05d2bac7cf7eda20055

In both cases they remove the deprecated ASTERISK_FILE_VERSION reference...
