### ISSUE TITLE
Multiple nodes within arrays

### ISSUE THREAD

**Issue by burn20sp** [drivefast/asterisk-res_json#7]
Hello!
I need to include many 'nodes' within an array. 
Example:
````json
{
  "array_level_1": [
    {
      "iten_1a": "value_1a",
      "iten_2a": "value_2a"
    },
    {
      "iten_1b": "value_1b",
      "iten_2b": "value_2b"
    }
  ]
}
````

A simple array (with values ​​only) I was able to apply. However, I couldn't reproduce the example.
I tried to create an array (`jsonadd(json,/,array,content)`) and then add the nodes (`jsonadd(json,/content,node,content1)`).
But the declared values ​​afterwards are not actually inserted (`jsonadd(json,/content/content1,string,var_1,value_1)`)

```json
{
  "content": [
    {},
    {},
    {},
    {}
  ]
}
````
I'm certainly making mistakes at some point. Could you point me in the right way?

I am very grateful for the help and I apologize for the English, as I am using the google translator.

**Comment by digas** [comment]
Hey @burn20sp , i believe my issue was somewhat similiar to yours some years ago.
please check this closed issue #1

**Comment by burn20sp** [comment]
Hey @digas. I checked your case carefully, but I think it is different.
You needed to create an array, what I need is to create several arrays within a node.

You intended to create like this:

``` json
{
  "array_level_1": 
    {
      "iten_1a": "value_1a",
      "iten_2a": "value_2a"
    }
}
```

I need to create multiple arrays inside `array_level_1`
```json
{
  "array_level_1": [
    {
      "iten_1a": "value_1a",
      "iten_2a": "value_2a"
    },
    {
      "iten_1b": "value_1b",
      "iten_2b": "value_2b"
    }
  ]
}
```
You may have this option in the application and it is just not described in the documentation. Unfortunately, I don't have much knowledge of the language used.
Anyway, thank you for trying to help.

**Comment by drivefast** [comment]
Hello @burn20sp , apologies for leaving this unattended, i may somehow accidentally deleted the notification at the time it was posted.
I see you already constructed an array of dictionaries, so you're on the right path. Further on, you need to refer the individual elements in the array as `/content/0`, `/content/1` and `/content/2`. Your array elements are dictionaries, so you would need to add key-value pairs there. To do that, use 
```
exten => s,n,jsonadd(json,content/0,string,item_1a,value_1a)
exten => s,n,jsonadd(json,content/0,string,item_2a,value_2a)
``` 
to fill the dictionary that is the first element in your array, and 
```
exten => s,n,jsonadd(json,content/1,string,item_1b,value_1b)
exten => s,n,jsonadd(json,content/1,string,item_2b,value_2b)
```
for the second.

Hope this helps.

**Comment by burn20sp** [comment]
This time I'm the one who apologizes for the delay.
I managed to add several objects within an array, but it was necessary to add the index as "node" before.

```
exten => s,n,jsonadd(json,content,node,0)
exten => s,n,jsonadd(json,content/0,string,item_1,value_1)

exten => s,n,jsonadd(json,content,node,1)
exten => s,n,jsonadd(json,content/1,string,item_2,value_2)
```

Remembering that it only works correctly if the "index" starts with 0 (zero).

Congratulations on the project initiative.
