### ISSUE TITLE
How I can install this package on Vicidial or Goautodial. 

### ISSUE THREAD

**Issue by amitoshseu** [drivefast/asterisk-res_json#8]
Hi, How I can install this package on Vicidial or Goautodial. In specifically how can installed this package on that machine where asterisk already been installed.

**Comment by drivefast** [comment]
You would have to recompile the asterisk engine that gets distributed with your packages. I am not familiar enough with the applications you mentioned to give good advice on them, sorry.

**Comment by amitoshseu** [comment]
Thanks for your opnion.

**Comment by amitoshseu** [comment]
Thanks for your opinion.
